---
title: " "
output: 
  github_document:
      fig_width: 10
      fig_height: 8
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Frequently Asked Questions

### File

**Where can we download these data sets from?**  
*The datasets can be downloaded from 3 sources - [CPCB website](https://app.cpcbccr.com/ccr/#/caaqm-dashboard-all/caaqm-landing), [OpenAQ](https://openaq.org/#/countries/IN?_k=5ecycz), and [AirNow](https://www.airnow.gov/international/us-embassies-and-consulates/#India).*

**Does this application work for Countries other than India?**  
*Yes, Any dataset from the 3 mentioned sources can be used in this application to analyze the data, the only important thing to remember is to choose the right time zone.*

**How to use the application?**   
*Please check [here](https://github.com/adithirgis/OpenSourceAirQualityApp) for a walk through.*

**Will this application read data from a reference monitor which is not from the sources mentioned in the application?**  
*No, this application can do post-processing of the data downloaded from the mentioned sources.*

**What are the different file formats which can be uploaded to this application?**  
*The data can be uploaded only in .csv or .xlsx format.*

**What is the naming convention of downloaded files?**  
*The File tab downloaded data is the hourly or daily average so "average.csv", while the summary statistics file has an extension of "summary.csv", and the diurnal table download will have an extension of "diurnal.csv".*

**What are the different packages used in the application?**  
*The different packages we use here are - tidyverse, ggplot2, openair, lubridate, shiny, bslib, forecast, biwavelet, readxl, DT, data.table, nortest, janitor, zoo.*

**Can the input file be manipulated/edited?**  
*No. our application is currently designed to read the preset format of the input file.* *Any alterations in the input file may lead to the malfunctioning of the application.*

**What is the standard outlier condition?**  
*The standard outlier detection condition is to find the daily mean and standard deviation and then removing values which are lower then Mean - x \* SD and greater than Mean + x \* SD, where x is any real number.*

**Why should we remove repeated consecutive measurements?**  
*Sometimes when the instrument breaks down, it tends to show exactly the same consecutive values, it is advised to remove these as well.*

**Why should we remove values above 9999 from the data?**  
*Usually, values above 9999 are incorrect, also because the instruments usually measure only up to 999 values in PM instruments. This can be removed using this filter option.*

**What are the available time resolutions for plots and tables?**  
*Only hourly and daily average plots can be generated in this application, although the data table can be of 60, 30, and 15 minutes time resolution.*

**How to export plots?**  
*To save the image right click on the plot and select save image as. You can save it on your local computer in .png or .jpeg format.*

**Can we upload datasets of different timezone?**  
*Yes, for data from OpenAQ and AirNow, different time formats are supported, just select the right timezone.*

**Are the plots customizable?**  
*Only the axis labels and Plot title can be customized.*

**Whom to contact for doubts or suggestions?**  
*We are happy to incorporate more features based on what users need. Write to us at [contact\@ilklabs.com](mailto:contact@ilklabs.com). For reporting any bug/issue click [here](https://github.com/adithirgis/OpenSourceAirQualityApp/issues).*

**Can the plots generated using PolluCheck be used for publications?**  
*Depends on the user. If you find the resolution and everything usable, please go ahead. Remember to cite us!*

**How to cite PolluCheck?**

**Is the theme of the application customizable?**  
*No, the theme of the app is not customizable, if you have any suggestions and resources, please PR in the github repo link provided above.*

### Summary

**What is the naming convention of the file downloaded?**  
*The data downloaded in this tab will have an extension of \_average.csv*.

### Summary Plots

**How to read the box plots?**  
*A boxplot is a way to show a [five-number summary](https://www.statisticshowto.com/statistics-basics/how-to-find-a-five-number-summary-in-statistics/) in a chart. The main part of the chart (the "box") shows where the middle portion of the data is: the interquartile range. At the ends of the box, you'll find the first [quartile](https://www.statisticshowto.com/what-are-quartiles/)(the 25% mark) and the third quartile (the 75% mark). The whiskers on the far most of the box plots show the minimum and maximum values in the datasets. Finally, the median is represented by a vertical bar in the center of the box. ([Source](https://www.statisticshowto.com/probability-and-statistics/descriptive-statistics/box-plot/))*

**What do the bars in the vertical bar plots indicate?**  
*The vertical bars represent mean + sd and mean - sd.*

**What are the bars in the diurnal plot and why are there two options?**  
*Diurnal plots represent the time of the day variability using mean (of that hour) and sd or median (of that hour) and IQR. So when you choose mean and sd the bars represent sd, while when you choose median and IQR, the bars represent IQR.*

**Can we plot ratios of different pollutants on a time series?**  
*No, this feature is not implemented yet.*

### Statistical Plots

**What is the difference between the Shapiro-Wilk normality test and the Anderson- Darling normality test?**  
*Shapiro-Wilk test is used to check for normality when the sample size is below 5000, while if you have data points above 5000, please check Anderson-Darling test.*

**How is the data imputed for trend analysis?**  
*For imputing values in the discontinuous data set we use [forecast package](https://cran.r-project.org/web/packages/forecast/forecast.pdf), please check the resource for more details.*

**What packages were used for Trend Analysis?**  
*Trend Analysis is available for daily values alone. For trend analysis using Mann-Kendall test we use [mk.test](https://www.rdocumentation.org/packages/trend/versions/1.1.4/topics/mk.test). For imputing values in the discontinuous data set we use [forecast package](https://cran.r-project.org/web/packages/forecast/forecast.pdf). For continuous wavelet transform we use [biwavelet package](https://cran.r-project.org/web/packages/biwavelet/biwavelet.pdf). In periodicity analysis, the contours covered by black lines represent the significant periodicity at 95% significant 519 level.*

**Why cant trend analysis be used for hourly data?**  
*Hourly data does not have much periodicity to be captured.*

**How Q-Q Plot is different from a Scatter Plot?**  
*A Q-Q plot is a scatterplot created by plotting two sets of quantiles against one another. If both sets of quantiles came from the same distribution, we should see the points forming a line that's roughly straight. ([Source](https://data.library.virginia.edu/understanding-q-q-plots/#:~:text=A%20Q%2DQ%20plot%20is%20a,truly%20come%20from%20Normal%20distributions.))*

### Linear Regression

**What are univariate and multivariate?**  
*Univariate regression is which consist of single independent variable while multivariate consist of three or more variables.*

**What is the difference between multiple R- square and R- square?**  
*Multiple R squared is simply a measure of Rsquared for models that have multiple predictor variables. Therefore it measures the amount of variation in the response variable that can be explained by the predictor variables. The fundamental point is that when you add predictors to your model, the multiple Rsquared will always increase, as a predictor will always explain some portion of the variance. Adjusted Rsquared controls against this increase, and adds penalties for the number of predictors in the model. Therefore it shows a balance between the most parsimonious model, and the best fitting model. Generally, if you have a large difference between your multiple and your adjusted Rsquared that indicates you may have overfit your model. [source](https://stats.stackexchange.com/questions/241283/what-is-the-main-difference-between-multiple-r-squared-and-adjusted-r-squared/241298)*

**How to check if the data is significant or not?**  
*The p-value in the last column tells you the significance of the regression coefficient for a given parameter. If the p-value is small enough to claim statistical significance, that just means there is strong evidence that the coefficient is different from 0, or else you could also try t-test. [source](https://stats.stackexchange.com/questions/37912/how-to-determine-which-variables-are-statistically-significant-in-multiple-regre)*

**What are residuals?**  
*The data points usually don't fall exactly on this regression equation line; they are scattered around. A residual is the vertical distance between a data point and the regression line. It tells us how well a line fits with an individual data point. [source](https://www.statisticshowto.com/residual/)*

**What are degrees of freedom?**  
*The degrees of freedom indicate the number of independent values that can vary in an analysis without breaking any constraints. [source](https://statisticsbyjim.com/hypothesis-testing/degrees-freedom-statistics/)*

### Compare

**Can I compare two datasets of different timezone?**  
*No, right now the comparison is with data from same timezone.*

**Can I compare two datasets of different time periods?**  
*Yes, you can check the time-series of both the datasets, but the scatter plot will not be generated as they belong to different time series.*

**Can I compare datasets from different downloading sources?**  
*Yes, you can definitely compare from different available sources.*

**How many datasets can be compared at a time in the application?**  
*As of now, only one single file can be compared to the uploaded dataset.*

**Is it possible to compare two datasets with different time resolutions?**  
*Yes! It is possible to compare datasets from different time resolution since the application averages to 1 hour or daily average.*

### openair

**What is the difference between "median and quantiles" and "mean and 95% confidence intervals" in Time Variation Plot?**  
*Since Time Variation plot shows the variation in parameters based on different time resolutions. It is the same option to time variation plots as mean and sd or median and IQR.*

**Is there a possibility to generate other openair plots?**  
*No, right now the application cannot generate other plots which can be generated using openair.*

**Where can I find the documentation of openair?**  
*Please click [here](https://cran.r-project.org/web/packages/openair/openair.pdf). Also, remember to cite them!*

**What are the ambient levels in India?**  
*Please check the graph below.*
