app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("test_OpenAQ")

app$setInputs(help_link = "click")
app$setInputs(switch_tab = "click")
app$setInputs(type = "oaq")
app$uploadFile(file1 = "OpenAQ.csv")
app$setInputs(remove_9 = TRUE)
app$setInputs(hourly = "click")
app$snapshot()
app$setInputs(avg_hour = "daily")
app$setInputs(hourly = "click")
app$snapshot()
app$setInputs(tabs1 = "2")
app$snapshot()
app$setInputs(tabs1 = "5")
app$setInputs(freq = "click")
app$setInputs(qq = "click")
app$snapshot()
app$setInputs(tabs1 = "6")
app$setInputs(reg = "click")
app$setInputs(InDepVar1 = "SO2")
app$setInputs(InDepVar1 = c("SO2", "NO2"))
app$setInputs(mulreg = "click")
app$snapshot()
app$setInputs(tabs1 = "7")
app$setInputs(type2 = "oaq")
app$uploadFile(file2 = "OpenAQ.csv")
app$setInputs(Para = "CO")
app$setInputs(plot_values = "click")
app$setInputs(plot_val = "click")
app$setInputs(plot_val_di = "click")
app$snapshot()
app$setInputs(tabs1 = "4")
app$setInputs(cp = "click")
app$setInputs(stat_tv = "median")
app$setInputs(tv = "click")
app$snapshot()

