app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("test_CPCB")

app$setInputs(help_link = "click")
app$setInputs(switch_tab = "click")
app$uploadFile(file1 = "BWSSB.xlsx")
app$setInputs(remove_9 = TRUE)
app$setInputs(repeated = TRUE)
app$setInputs(exclude = TRUE)
app$setInputs(percent = TRUE)
app$setInputs(hourly = "click")
app$snapshot()
app$setInputs(tabs1 = "2")
app$snapshot()
app$setInputs(tabs1 = "3")
app$setInputs(da = "click")
app$setInputs(ts = "click")
app$setInputs(box = "click")
app$setInputs(box = "click")
app$setInputs(mbox = "click")
app$setInputs(boxt = "click")
app$setInputs(diurnal = "click")
app$snapshot()
app$setInputs(tabs1 = "5")
app$setInputs(freq = "click")
app$setInputs(qq = "click")
app$setInputs(acf = "click")
app$setInputs(mk = "click")
app$setInputs(ta = "click")
app$snapshot()
app$setInputs(tabs1 = "6")
app$setInputs(InDepVar = "PM10")
app$setInputs(reg = "click")
app$setInputs(InDepVar1 = "PM10")
app$setInputs(InDepVar1 = c("PM10", "ratio"))
app$setInputs(mulreg = "click")
app$snapshot()
app$setInputs(tabs1 = "7")
app$uploadFile(file2 = "BWSSB.xlsx")
app$setInputs(Para = "PM10")
app$setInputs(plot_values = "click")
app$setInputs(plot_val = "click")
app$setInputs(plot_val_di = "click")
app$snapshot()
app$setInputs(tabs1 = "4")
app$setInputs(cp = "click")
app$setInputs(tv = "click")
app$setInputs(stat_tv = "median")
app$snapshot()
app$setInputs(tabs1 = "5")
app$setInputs(avg_hour2 = "daily2")
app$setInputs(freq = "click")
app$setInputs(qq = "click")
app$setInputs(acf = "click")
app$snapshot()

