app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("test_AirNow")

app$setInputs(type = "an")
app$uploadFile(file1 = "AirNow.csv")
app$setInputs(remove_9 = TRUE)
app$setInputs(avg_hour = "daily")
app$setInputs(hourly = "click")
app$snapshot()
app$setInputs(tabs1 = "2")
app$setInputs(avg = "monthly")
app$snapshot()
app$setInputs(tabs1 = "3")
app$setInputs(da = "click")
app$setInputs(ts = "click")
app$setInputs(box = "click")
app$setInputs(mbox = "click")
app$setInputs(boxt = "click")
app$setInputs(diurnal = "click")
app$setInputs(diurn = "mon")
app$setInputs(diurnal = "click")
app$snapshot()
app$setInputs(tabs1 = "5")
app$setInputs(freq = "click")
app$setInputs(qq = "click")
app$setInputs(acf = "click")
app$setInputs(mk = "click")
app$setInputs(ta = "click")
app$snapshot()
app$setInputs(tabs1 = "7")
app$setInputs(type2 = "an")
app$uploadFile(file2 = "AirNow.csv")
app$setInputs(plot_values = "click")
app$setInputs(plot_val = "click")
app$setInputs(plot_val_di = "click")
app$setInputs(diur1 = "mediq")
app$setInputs(diurn1 = "mon")
app$setInputs(plot_val_di = "click")
app$snapshot()
app$setInputs(tabs1 = "4")
app$setInputs(cp = "click")
app$setInputs(tv = "click")
app$setInputs(stat_tv = "median")
app$snapshot()
app$setInputs(tabs1 = "FAQ's")
app$snapshot()
