app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("test_AirNow")

app$setInputs(help_link = "click")
app$setInputs(switch_tab = "click")
app$setInputs(type = "an")
app$uploadFile(file1 = "AirNow.csv")
app$setInputs(hourly = "click")
app$snapshot()
app$setInputs(tabs1 = "3")
app$setInputs(da = "click")
app$setInputs(ts = "click")
app$setInputs(box = "click")
app$setInputs(mbox = "click")
app$setInputs(boxt = "click")
app$setInputs(diurnal = "click")
app$snapshot()
app$setInputs(tabs1 = "6")
app$setInputs(reg = "click")
app$setInputs(InDepVar1 = "PM2.5")
app$snapshot()
app$setInputs(tabs1 = "7")
app$setInputs(type2 = "an")
app$uploadFile(file2 = "AirNow.csv")
app$setInputs(plot_values = "click")
app$setInputs(plot_val = "click")
app$setInputs(plot_val_di = "click")
app$snapshot()
app$setInputs(tabs1 = "4")
app$setInputs(cp = "click")
app$setInputs(tv = "click")
app$snapshot()
app$setInputs(stat_tv = "median")
app$setInputs(tv = "click")
app$snapshot()

